package com.adminsures.sures.enums;

public enum Estado {
    AGUASCALIENTES, BAJA_CALIFORNIA, BAJA_CALIFORNIA_SUR, CAMPECHE, CHIAPAS, CHIHUAHUA, COAHUILA,
    COLIMA, CDMX, DURANGO, GUANAJUATO, GUERRERO, HIDALGO, JALISCO, MEXICO, MICHOACAN,
    MORELOS, NAYARIT, NUEVO_LEON, OAXACA, PUEBLA, QUERETARO, QUINTANA_ROO, SAN_LUIS_POTOSI,
    SINALOA, SONORA, TABASCO, TAMAULIPAS, TLAXCALA, VERACRUZ, YUCATAN, ZACATECAS
}
